# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\yadda\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\PoleAerien\interfaces\PoleAerien_apropos.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(750, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AboutDialog.sizePolicy().hasHeightForWidth())
        AboutDialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/PoleAerien/images/icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AboutDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(AboutDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.about = QtWidgets.QLabel(AboutDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.about.sizePolicy().hasHeightForWidth())
        self.about.setSizePolicy(sizePolicy)
        self.about.setMinimumSize(QtCore.QSize(120, 50))
        self.about.setMaximumSize(QtCore.QSize(91, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.about.setFont(font)
        self.about.setObjectName("about")
        self.horizontalLayout_3.addWidget(self.about)
        self.logo = QtWidgets.QLabel(AboutDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(70, 79))
        self.logo.setMaximumSize(QtCore.QSize(70, 79))
        self.logo.setObjectName("logo")
        self.horizontalLayout_3.addWidget(self.logo)
        self.logo_2 = QtWidgets.QLabel(AboutDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_2.sizePolicy().hasHeightForWidth())
        self.logo_2.setSizePolicy(sizePolicy)
        self.logo_2.setMinimumSize(QtCore.QSize(70, 79))
        self.logo_2.setMaximumSize(QtCore.QSize(70, 79))
        self.logo_2.setObjectName("logo_2")
        self.horizontalLayout_3.addWidget(self.logo_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.version = QtWidgets.QLabel(AboutDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.version.sizePolicy().hasHeightForWidth())
        self.version.setSizePolicy(sizePolicy)
        self.version.setMinimumSize(QtCore.QSize(90, 25))
        self.version.setMaximumSize(QtCore.QSize(90, 25))
        self.version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.version.setObjectName("version")
        self.horizontalLayout.addWidget(self.version)
        self.version_n = QtWidgets.QLabel(AboutDialog)
        self.version_n.setMinimumSize(QtCore.QSize(100, 25))
        self.version_n.setObjectName("version_n")
        self.horizontalLayout.addWidget(self.version_n)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.autors = QtWidgets.QLabel(AboutDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autors.sizePolicy().hasHeightForWidth())
        self.autors.setSizePolicy(sizePolicy)
        self.autors.setMinimumSize(QtCore.QSize(90, 25))
        self.autors.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.autors.setObjectName("autors")
        self.horizontalLayout_2.addWidget(self.autors)
        self.autors_name = QtWidgets.QLabel(AboutDialog)
        self.autors_name.setMinimumSize(QtCore.QSize(180, 25))
        self.autors_name.setObjectName("autors_name")
        self.horizontalLayout_2.addWidget(self.autors_name)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_editeur = QtWidgets.QHBoxLayout()
        self.horizontalLayout_editeur.setObjectName("horizontalLayout_editeur")
        self.editeur_label = QtWidgets.QLabel(AboutDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editeur_label.sizePolicy().hasHeightForWidth())
        self.editeur_label.setSizePolicy(sizePolicy)
        self.editeur_label.setMinimumSize(QtCore.QSize(90, 25))
        self.editeur_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.editeur_label.setObjectName("editeur_label")
        self.horizontalLayout_editeur.addWidget(self.editeur_label)
        self.editeur_name = QtWidgets.QLabel(AboutDialog)
        self.editeur_name.setMinimumSize(QtCore.QSize(180, 25))
        self.editeur_name.setObjectName("editeur_name")
        self.horizontalLayout_editeur.addWidget(self.editeur_name)
        self.verticalLayout.addLayout(self.horizontalLayout_editeur)
        self.textBrowser_3 = QtWidgets.QTextBrowser(AboutDialog)
        self.textBrowser_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_3.sizePolicy().hasHeightForWidth())
        self.textBrowser_3.setSizePolicy(sizePolicy)
        self.textBrowser_3.setMinimumSize(QtCore.QSize(263, 121))
        self.textBrowser_3.setMaximumSize(QtCore.QSize(261, 121))
        self.textBrowser_3.setLineWidth(2)
        self.textBrowser_3.setOpenExternalLinks(True)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.verticalLayout.addWidget(self.textBrowser_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_help = QtWidgets.QLabel(AboutDialog)
        self.label_help.setMinimumSize(QtCore.QSize(0, 25))
        self.label_help.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_help.setObjectName("label_help")
        self.verticalLayout_2.addWidget(self.label_help)
        self.textBrowser_2 = QtWidgets.QTextBrowser(AboutDialog)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout_2.addWidget(self.textBrowser_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(AboutDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)

        self.retranslateUi(AboutDialog)
        self.buttonBox.rejected.connect(AboutDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "POLE AERIEN - A propos"))
        self.about.setText(_translate("AboutDialog", "POLE AERIEN"))
        self.logo.setText(_translate("AboutDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/plugins/PoleAerien/images/logo_NGE.svg\" /></p></body></html>"))
        self.logo_2.setText(_translate("AboutDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/plugins/PoleAerien/images/icon.svg\" width=\"64\" height=\"64\" /></p></body></html>"))
        self.version.setText(_translate("AboutDialog", "Version :"))
        self.version_n.setText(_translate("AboutDialog", "2.2.1"))
        self.autors.setText(_translate("AboutDialog", "Auteur :"))
        self.autors_name.setText(_translate("AboutDialog", "NGE ES"))
        self.editeur_label.setText(_translate("AboutDialog", "Editeur :"))
        self.editeur_name.setText(_translate("AboutDialog", "Youcef ADDA"))
        self.textBrowser_3.setHtml(_translate("AboutDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><style type=\"text/css\">\n"
"p { margin: 4px 0; }\n"
"a { color: #4ecca3; }\n"
"</style></head><body>\n"
"<p align=\"center\" style=\"font-size:10pt; font-weight:bold; color:#f8b500;\">Liens utiles</p>\n"
"<p align=\"center\"><a href=\"https://leportail.nge.fr/\">leportail.nge.fr</a></p>\n"
"<p align=\"center\"><a href=\"https://www.nge.fr/filiales/nge-infranet\">nge.fr/filiales/nge-infranet</a></p>\n"
"<p align=\"center\" style=\"margin-top:12px; font-size:10pt; font-weight:bold; color:#f8b500;\">Support</p>\n"
"<p align=\"center\"><a href=\"https://teams.microsoft.com/v2/#/?lm=deeplink&amp;lmsrc=officeWaffle&amp;login_hint_safe=yadda@ext.nge.fr\">Teams - Youcef ADDA</a></p>\n"
"<p align=\"center\"><a href=\"mailto:yadda@ext.nge.fr\">yadda@ext.nge.fr</a></p>\n"
"</body></html>"))
        self.label_help.setText(_translate("AboutDialog", "Guide d\'utilisation"))
        self.textBrowser_2.setHtml(_translate("AboutDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><style type=\"text/css\">\n"
"p { margin: 6px 0; line-height: 1.4; }\n"
".title { font-size: 12pt; font-weight: bold; color: #e94560; }\n"
".highlight { color: #4ecca3; font-weight: bold; }\n"
".keyword { background: rgba(78, 204, 163, 0.2); padding: 2px 6px; border-radius: 3px; color: #4ecca3; }\n"
"</style></head><body>\n"
"<p><span class=\"title\">POLE AERIEN</span> est un outil de verification des donnees <span class=\"highlight\">CAP_FT</span> et <span class=\"highlight\">COMAC</span> par rapport aux etudes NGE.</p>\n"
"\n"
"<p style=\"font-weight:bold; color:#f8b500;\">Fonctionnalites :</p>\n"
"<p>- Controler les <span class=\"highlight\">FICHES APPUIS (FT)</span> par rapport aux poteaux Orange</p>\n"
"<p>- Controler les exports <span class=\"highlight\">COMAC (BT)</span> par rapport aux poteaux ENEDIS</p>\n"
"<p>- Exporter les <span class=\"highlight\">resultats d\'analyses</span> en fichier Excel</p>\n"
"\n"
"<p style=\"margin-top:16px; font-weight:bold; color:#f8b500;\">Mots cles :</p>\n"
"<p><span class=\"keyword\">Poteau</span> <span class=\"keyword\">BT</span> <span class=\"keyword\">COMAC</span> <span class=\"keyword\">NGE</span> <span class=\"keyword\">ENEDIS</span></p>\n"
"\n"
"<p style=\"margin-top:16px;\"><a href=\"docs/index.html\" style=\"color:#4ecca3; font-weight:bold;\">Documentation complete</a></p>\n"
"</body></html>"))
