# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CapComac
                                 A QGIS plugin
 Controle de donner comac
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-03-01
        copyright            : (C) 2022 by SOUMARE Abdoulayi
        email                : abdoulayisoumare@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


class Initiatlisation:

    def __init__(self):
        """Le constructeur de ma classe
        Il prend pour attribut de classe les *** """

    def name(self):
        return f"Pôle Aérien"

    def version(self):
        return "1"

    def description(self):
        return f"Contrôle de donner COMAC rélatif au poteau ENEDIS (POT-BT)"

    def qgisMinimumVersion(self):
        return "3.0"

    def experimental(self):
        return True

    def author(self):
        return f"SOUMARE Abdoulayi"

    def authorName(self):
        return self.author()

    def email(self):
        return "abdoulayisoumare@gmail.com"

    def icon(self):
        return "images/icon.png"


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CapComac class from file CapComac.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .PoleAerien import PoleAerien
    return PoleAerien(iface)
